# -*- coding: utf-8 -*-
"""sizganov.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P4byWNe4xiJUBR4xtDSM3ssJEste_BK0
"""

print ("Привет, мир!")